/// Flutter icons Imgcrop
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Imgcrop
///      fonts:
///       - asset: fonts/Imgcrop.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Imgcrop {
  Imgcrop._();

  static const _kFontFam = 'Imgcrop';

  static const IconData picture_outline = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData text = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData assessment = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData account = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData pdf = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe808, fontFamily: _kFontFam);
}
